/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_c_learn_MainActivity */

#ifndef _Included_com_example_administrator_c_learn_MainActivity
#define _Included_com_example_administrator_c_learn_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_c_learn_MainActivity
 * Method:    getDataLocal
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_c_1learn_MainActivity_getDataLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_administrator_c_learn_MainActivity
 * Method:    setDataLocal
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_c_1learn_MainActivity_setDataLocal
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
